/** 외국인 형사·가사센터 등록 (scratchpad fc/install.py 가 만듦. 직접 고치지 말 것) */
import type { Center } from "@/lib/centers"
import { crimeEn } from "@/lib/center-data/crime-en"
import crimeEnPages from "@/content/center-pages/crime-en.json"
import { familyEn } from "@/lib/center-data/family-en"
import familyEnPages from "@/content/center-pages/family-en.json"
import { crimeZh } from "@/lib/center-data/crime-zh"
import crimeZhPages from "@/content/center-pages/crime-zh.json"
import { familyZh } from "@/lib/center-data/family-zh"
import familyZhPages from "@/content/center-pages/family-zh.json"
import { crimeVi } from "@/lib/center-data/crime-vi"
import crimeViPages from "@/content/center-pages/crime-vi.json"
import { familyVi } from "@/lib/center-data/family-vi"
import familyViPages from "@/content/center-pages/family-vi.json"
import { crimeRu } from "@/lib/center-data/crime-ru"
import crimeRuPages from "@/content/center-pages/crime-ru.json"
import { familyRu } from "@/lib/center-data/family-ru"
import familyRuPages from "@/content/center-pages/family-ru.json"
import { crimeMn } from "@/lib/center-data/crime-mn"
import crimeMnPages from "@/content/center-pages/crime-mn.json"
import { familyMn } from "@/lib/center-data/family-mn"
import familyMnPages from "@/content/center-pages/family-mn.json"

export const intlCenters: Center[] = [crimeEn, familyEn, crimeZh, familyZh, crimeVi, familyVi, crimeRu, familyRu, crimeMn, familyMn]
export const intlCenterPages: unknown[] = [crimeEnPages, familyEnPages, crimeZhPages, familyZhPages, crimeViPages, familyViPages, crimeRuPages, familyRuPages, crimeMnPages, familyMnPages]
